// Dummy data generator for testing the sequence system

export function generateDummyContacts() {
  const today = new Date();

  return [
    // Contact 1: Never contacted (should show "NEW PROSPECT")
    {
      id: 'dummy_1',
      companyName: 'Acme Manufacturing',
      phone: '(555) 123-4567',
      website: 'https://acme-mfg.com',
      address: '123 Industrial Blvd, Chicago, IL',
      linkedin: 'https://linkedin.com/company/acme-mfg',
      industry: 'Manufacturing',
      callHistory: [],
      totalDials: 0,
      lastCall: null,
      nextFollowUp: null,
      currentOkCode: null,
      needsEmail: false,
      status: 'active',
      createdAt: new Date().toISOString(),
      sequence_status: 'never_contacted',
      sequence_current_day: 0,
      sequence_start_date: null,
      last_contact_date: null,
      has_email: true,
      has_linkedin: true,
      has_social_media: true,
      calls_made: 0,
      voicemails_left: 0,
      emails_sent: 0,
      linkedin_dms_sent: 0,
      linkedin_comments_made: 0,
      social_reactions: 0,
      social_comments: 0,
      physical_mail_sent: false,
      dead_reason: null,
      converted_date: null
    },

    // Contact 2: Active on Day 1 with pending tasks
    {
      id: 'dummy_2',
      companyName: 'TechCorp Solutions',
      phone: '(555) 234-5678',
      website: 'https://techcorp.io',
      address: '456 Silicon Way, San Francisco, CA',
      linkedin: 'https://linkedin.com/company/techcorp',
      industry: 'Technology',
      callHistory: [
        {
          date: today.toISOString(),
          outcome: 'DM',
          okCode: 'Interested - Follow Up',
          notes: 'Spoke with CEO, interested in learning more',
          duration: 180,
          hadConversation: true,
          hadTriage: false,
          objection: ''
        }
      ],
      totalDials: 1,
      lastCall: today.toISOString(),
      nextFollowUp: null,
      currentOkCode: 'Interested - Follow Up',
      needsEmail: false,
      status: 'active',
      createdAt: new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      sequence_status: 'active',
      sequence_current_day: 1,
      sequence_start_date: today.toISOString().split('T')[0],
      last_contact_date: today.toISOString().split('T')[0],
      has_email: true,
      has_linkedin: true,
      has_social_media: true,
      calls_made: 1,
      voicemails_left: 0,
      emails_sent: 0,
      linkedin_dms_sent: 0,
      linkedin_comments_made: 0,
      social_reactions: 0,
      social_comments: 0,
      physical_mail_sent: false,
      dead_reason: null,
      converted_date: null
    },

    // Contact 3: Active on Day 5 with some completed tasks
    {
      id: 'dummy_3',
      companyName: 'Global Logistics Inc',
      phone: '(555) 345-6789',
      website: 'https://globallogistics.com',
      address: '789 Freight St, Atlanta, GA',
      linkedin: 'https://linkedin.com/company/global-logistics',
      industry: 'Logistics',
      callHistory: [
        {
          date: new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
          outcome: 'DM',
          okCode: 'Callback Requested',
          notes: 'Good conversation, wants to talk next week',
          duration: 240,
          hadConversation: true,
          hadTriage: true,
          objection: ''
        }
      ],
      totalDials: 1,
      lastCall: new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      nextFollowUp: null,
      currentOkCode: 'Callback Requested',
      needsEmail: false,
      status: 'active',
      createdAt: new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      sequence_status: 'active',
      sequence_current_day: 5,
      sequence_start_date: new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      last_contact_date: new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      has_email: true,
      has_linkedin: true,
      has_social_media: false,
      calls_made: 1,
      voicemails_left: 0,
      emails_sent: 2,
      linkedin_dms_sent: 1,
      linkedin_comments_made: 0,
      social_reactions: 0,
      social_comments: 0,
      physical_mail_sent: false,
      dead_reason: null,
      converted_date: null
    },

    // Contact 4: Active on Day 10
    {
      id: 'dummy_4',
      companyName: 'Prime Retail Group',
      phone: '(555) 456-7890',
      website: 'https://primeretail.com',
      address: '321 Commerce Pkwy, Dallas, TX',
      linkedin: null,
      industry: 'Retail',
      callHistory: [
        {
          date: new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
          outcome: 'DM',
          okCode: 'Interested - Follow Up',
          notes: 'Left voicemail, they called back',
          duration: 120,
          hadConversation: false,
          hadTriage: false,
          objection: ''
        }
      ],
      totalDials: 1,
      lastCall: new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      nextFollowUp: null,
      currentOkCode: 'Interested - Follow Up',
      needsEmail: true,
      status: 'active',
      createdAt: new Date(today.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      sequence_status: 'active',
      sequence_current_day: 10,
      sequence_start_date: new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      last_contact_date: new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      has_email: true,
      has_linkedin: false, // No LinkedIn, so those tasks will be skipped
      has_social_media: true,
      calls_made: 1,
      voicemails_left: 1,
      emails_sent: 3,
      linkedin_dms_sent: 0,
      linkedin_comments_made: 0,
      social_reactions: 2,
      social_comments: 1,
      physical_mail_sent: false,
      dead_reason: null,
      converted_date: null
    },

    // Contact 5: Paused sequence
    {
      id: 'dummy_5',
      companyName: 'BlueSky Consulting',
      phone: '(555) 567-8901',
      website: 'https://bluesky-consult.com',
      address: '654 Strategy Ln, Boston, MA',
      linkedin: 'https://linkedin.com/company/bluesky',
      industry: 'Consulting',
      callHistory: [
        {
          date: new Date(today.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
          outcome: 'DM',
          okCode: 'Not Interested - Budget',
          notes: 'Timing not right, check back in Q2',
          duration: 90,
          hadConversation: true,
          hadTriage: false,
          objection: 'Budget constraints'
        }
      ],
      totalDials: 1,
      lastCall: new Date(today.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      nextFollowUp: null,
      currentOkCode: 'Not Interested - Budget',
      needsEmail: false,
      status: 'active',
      createdAt: new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      sequence_status: 'paused',
      sequence_current_day: 8,
      sequence_start_date: new Date(today.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      last_contact_date: new Date(today.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      has_email: true,
      has_linkedin: true,
      has_social_media: true,
      calls_made: 1,
      voicemails_left: 0,
      emails_sent: 2,
      linkedin_dms_sent: 1,
      linkedin_comments_made: 1,
      social_reactions: 1,
      social_comments: 1,
      physical_mail_sent: false,
      dead_reason: null,
      converted_date: null
    },

    // Contact 6: Converted to client
    {
      id: 'dummy_6',
      companyName: 'Apex Industries',
      phone: '(555) 678-9012',
      website: 'https://apex-ind.com',
      address: '987 Corporate Dr, Seattle, WA',
      linkedin: 'https://linkedin.com/company/apex-industries',
      industry: 'Manufacturing',
      callHistory: [
        {
          date: new Date(today.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
          outcome: 'DM',
          okCode: 'Meeting Scheduled',
          notes: 'Demo went great, ready to sign!',
          duration: 600,
          hadConversation: true,
          hadTriage: true,
          objection: ''
        }
      ],
      totalDials: 3,
      lastCall: new Date(today.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      nextFollowUp: null,
      currentOkCode: 'Meeting Scheduled',
      needsEmail: false,
      status: 'client',
      createdAt: new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      sequence_status: 'converted',
      sequence_current_day: 15,
      sequence_start_date: new Date(today.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      last_contact_date: new Date(today.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      has_email: true,
      has_linkedin: true,
      has_social_media: true,
      calls_made: 3,
      voicemails_left: 1,
      emails_sent: 4,
      linkedin_dms_sent: 2,
      linkedin_comments_made: 3,
      social_reactions: 4,
      social_comments: 2,
      physical_mail_sent: false,
      dead_reason: null,
      converted_date: today.toISOString().split('T')[0]
    },

    // Contact 7: Another active on Day 1
    {
      id: 'dummy_7',
      companyName: 'NextGen Software',
      phone: '(555) 789-0123',
      website: 'https://nextgen-soft.com',
      address: '147 Innovation Way, Austin, TX',
      linkedin: 'https://linkedin.com/company/nextgen-software',
      industry: 'Software',
      callHistory: [
        {
          date: today.toISOString(),
          outcome: 'GK',
          okCode: 'Gatekeeper Block',
          notes: 'Receptionist, need to find DM',
          duration: 60,
          hadConversation: false,
          hadTriage: false,
          objection: ''
        }
      ],
      totalDials: 1,
      lastCall: today.toISOString(),
      nextFollowUp: null,
      currentOkCode: 'Gatekeeper Block',
      needsEmail: false,
      status: 'active',
      createdAt: new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      sequence_status: 'active',
      sequence_current_day: 1,
      sequence_start_date: today.toISOString().split('T')[0],
      last_contact_date: today.toISOString().split('T')[0],
      has_email: true,
      has_linkedin: true,
      has_social_media: true,
      calls_made: 1,
      voicemails_left: 0,
      emails_sent: 0,
      linkedin_dms_sent: 0,
      linkedin_comments_made: 0,
      social_reactions: 0,
      social_comments: 0,
      physical_mail_sent: false,
      dead_reason: null,
      converted_date: null
    },

    // Contact 8: Never contacted (another prospect)
    {
      id: 'dummy_8',
      companyName: 'Coastal Shipping Co',
      phone: '(555) 890-1234',
      website: 'https://coastal-ship.com',
      address: '258 Harbor Rd, Miami, FL',
      linkedin: 'https://linkedin.com/company/coastal-shipping',
      industry: 'Shipping',
      callHistory: [],
      totalDials: 0,
      lastCall: null,
      nextFollowUp: null,
      currentOkCode: null,
      needsEmail: false,
      status: 'active',
      createdAt: new Date().toISOString(),
      sequence_status: 'never_contacted',
      sequence_current_day: 0,
      sequence_start_date: null,
      last_contact_date: null,
      has_email: true,
      has_linkedin: true,
      has_social_media: false,
      calls_made: 0,
      voicemails_left: 0,
      emails_sent: 0,
      linkedin_dms_sent: 0,
      linkedin_comments_made: 0,
      social_reactions: 0,
      social_comments: 0,
      physical_mail_sent: false,
      dead_reason: null,
      converted_date: null
    }
  ];
}
